# .github/workflows/i18n.yml
name: i18n QA

on:
  pull_request:
    paths:
      - "src/i18n/messages/**.json"
      - "scripts/i18n-*.ts"
      - ".github/workflows/i18n.yml"

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: i18n sync (dry-run)
        run: npm run i18n:sync:dry
      - name: i18n lint
        run: npm run i18n:lint:ci
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: i18n-reports
          path: .reports/

